[package]
name = "diol"
version = "0.4.1"
edition = "2021"
authors = ["sarah <>"]
description = "benchmark lib"
readme = "README.md"
repository = "https://github.com/sarah-ek/diol/"
license = "MIT"
keywords = ["benchmark"]

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
dyn-clone = "1.0.17"
equator = "0.2.0"
plotters = "0.3.5"
regex = "1.10.4"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"

[dev-dependencies]
popcnt = "0.1.0"
